<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <AssemblyName>Contents.Domain</AssemblyName>
    <RootNamespace>Contents.Domain</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

</Project>
