<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <AssemblyName>Contents.Infrastructure</AssemblyName>
    <RootNamespace>Contents.Infrastructure</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
      <ProjectReference Include="..\..\..\Shared\Shared.csproj" />
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql" Version="10.0.3" />
    </ItemGroup>

</Project>
