<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" Version="4.0.103.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Application\Contracts\" />
    </ItemGroup>

</Project>
