<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <AssemblyName>Identity.Contracts</AssemblyName>
    <RootNamespace>Identity.Contracts</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Contract</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

</Project>
